"""Declarative base + shared naming convention for Alembic-friendly migrations."""
from __future__ import annotations

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# A fixed naming convention makes autogenerated Alembic migrations stable
# and reversible (constraint names don't change randomly between runs).
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base class for all trading-system ORM models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
